openapi: 3.0.2
info:
  title: MNC duit API
  description: MNC duit API
  version: 0.1.0
  license:
    name: Proprietary
servers:
  - url: http://localhost:8000
paths:
  /post:
    get:
      description: Get Post
      tags:
        - Post
      parameters:
        - name: post_type
          in: query
          description: |-
              Post type
          required: true
          schema:
            type: string
            enum: [POSTER,GUIDANCE,NEWS]
        - name: order_by
          in: query
          description: |-
              Order By
          required: false
          schema:
            type: string
            enum: [post_title,post_publish_thru,post_publish_start]
        - name: order_type
          in: query
          description: |-
              Order Type
          required: false
          schema:
            type: string
            enum: [ASC,DESC]
        - name: limit
          in: query
          description: |-
              Number of post (max 100 or choose no limit)
          required: false
          schema:
            type: integer
        - name: page
          in: query
          description: |-
              Page
          required: false
          schema:
            type: integer  
        - name: nolimit
          in: query
          description: |-
              Ignore limit and page
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                {
                  "status": {
                    "code": 200,
                    "message_server": "OK",
                    "message_client": "OK"
                  },
                  "data": {
                    "post_type_key": 3,
                    "post_type_code": "NEWS",
                    "post_type_name": "News",
                    "post_type_desc": "Berbagai berita-berita",
                    "post_type_group": "HOME",
                    "post_list": [{
                      "post_key": 2,
                      "post_subtype": {
                        "post_subtype_key": 1,
                        "post_subtype_code": "GENERAL",
                        "post_subtype_name": "Category General"
                      },
                      "post_title": "Investasi Jangan Hanya Mimpi",
                      "post_sub_title": "Wujudkan impian anda dengan mulai berinvestasi sebesar 100.00",
                      "post_content": "Investasi masa kini semakin mudah. MNC Asset Mnanagement menyediakan kemudahan untuk investasi bagi nasabah retail mulai dari 100.000",
                      "post_content_author": null,
                      "post_content_sources": null,
                      "post_publish_start": "31 Dec 2050",
                      "post_publish_thru": "",
                      "post_page_allowed": false,
                      "post_comment_allowed": false,
                      "post_comment_displayed": false,
                      "post_files_allowed": false,
                      "post_video_allowed": false,
                      "post_video_url": null,
                      "post_pinned": false
                    }]
                  }
                }
        '400':
          description: Bad request
          content:
            text/plain:
              example: Missing required parameter
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: ""
        '500':
          description: Internal server error
          content:
            text/plain:
              example: Error parsing data
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Custom
