openapi: 3.0.2
info:
  title: MNC duit API
  description: MNC duit API
  version: 0.1.0
  license:
    name: Proprietary
servers:
  - url: http://127.0.0.1:8000
paths:
  /register:
      post:
        description: Register MNCDuit
        tags:
          - Session
        requestBody:
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  password:
                    type: string
                  phone:
                    type: string
                required:
                  - email
                  - password
                  - phone
        responses:
          '200':
            description: Success register
            content:
              text/plain:
                example: 
                  {
                    "status": {
                        "code": 200,
                        "message_server": "OK",
                        "message_client": "OK"
                    },
                    "data": {
                        "ulogin_email": "riotesting92@gmail.com",
                        "ulogin_mobileno": "08388644366"
                    }
                  }
          '400':
            description: Bad request
            content:
              text/plain:
                example: Email is not valid
          '500':
            description: Internal server error
            content:
              text/plain:
                example: Error get email
  /verifyemail:
    post:
      description: Verify email of LidoPlayer account
      tags:
        - Session
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                token:
                  type: string
              required:
                - token
      responses:
        '201':
          description: Success
          content:
            text/plain:
              example: Success verify email
        '400':
          description: Bad request
          content:
            text/plain:
              example: Missing required parameter
        '403':
          description: Forbidden
          content:
            text/plain:
              example: Token is expired
        '404':
          description: Not found
          content:
            text/plain:
              example: Token not found
        '500':
          description: Internal server error
          content:
            text/plain:
              example: Error get email
  /verifyotp:
    post:
      description: Verify otp of MNCduit account
      tags:
        - Session
      requestBody:
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  otp:
                    type: string
                required:
                  - otp
      responses:
        '201':
          description: Success
          content:
            text/plain:
              example: Success verify mobile phone
        '400':
          description: Bad request
          content:
            text/plain:
              example: Missing required parameter
        '403':
          description: Forbidden
          content:
            text/plain:
              example: OTP is expired
        '404':
          description: Not found
          content:
            text/plain:
              example: OTP not found
        '500':
          description: Internal server error
          content:
            text/plain:
              example: Error get email
  /login:
      post:
        description: Login MNCDuit
        tags:
          - Session
        requestBody:
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  password:
                    type: string
                required:
                  - email
                  - password
        responses:
          '200':
            description: Success register
            content:
              text/plain:
                example: 
                  {
                    "status": {
                        "code": 200,
                        "message_server": "OK",
                        "message_client": "OK"
                    },
                    "data": {
                        "session_id": "17hhoIH8sdUugW92bJBfpNaldkNLsd",
                        "email": "yogasutrisna@gmail.com",
                        "expired": "2006-01-02T15:04:05+00:00"
                    }
                  }
          '400':
            description: Bad request
            content:
              text/plain:
                example: Missing required parameter
          '500':
            description: Internal server error
            content:
              text/plain:
                example: Login failed
  /posts/{field}/{key}:
    get:
      description: Get Post
      tags:
        - Post
      parameters:
        - name: field
          in: path
          description: |-
              
          required: true
          schema:
            type: string
            enum: [type,subtype]
        - name: key
          in: path
          description: |-
              post type ker or post subtype key
          required: true
          schema:
            type: integer
        - name: order_by
          in: query
          description: |-
              Order By
          required: false
          schema:
            type: string
            enum: [post_title,post_publish_thru,post_publish_start]
        - name: order_type
          in: query
          description: |-
              Order Type
          required: false
          schema:
            type: string
            enum: [ASC,DESC]
        - name: limit
          in: query
          description: |-
              Number of post (max 100 or choose no limit)
          required: false
          schema:
            type: integer
        - name: page
          in: query
          description: |-
              Page
          required: false
          schema:
            type: integer  
        - name: nolimit
          in: query
          description: |-
              Ignore limit and page
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                {
                  "status": {
                    "code": 200,
                    "message_server": "OK",
                    "message_client": "OK"
                  },
                  "data": {
                    "post_type_key": 3,
                    "post_type_code": "NEWS",
                    "post_type_name": "News",
                    "post_type_desc": "Berbagai berita-berita",
                    "post_type_group": "HOME",
                    "post_list": [{
                      "post_key": 2,
                      "post_subtype": {
                        "post_subtype_key": 1,
                        "post_subtype_code": "GENERAL",
                        "post_subtype_name": "Category General"
                      },
                      "post_title": "Investasi Jangan Hanya Mimpi",
                      "post_sub_title": "Wujudkan impian anda dengan mulai berinvestasi sebesar 100.00",
                      "post_content": "Investasi masa kini semakin mudah. MNC Asset Mnanagement menyediakan kemudahan untuk investasi bagi nasabah retail mulai dari 100.000",
                      "post_content_author": null,
                      "post_content_sources": null,
                      "post_publish_start": "31 Dec 2020",
                      "post_publish_thru": "31 Dec 2021",
                      "post_page_allowed": false,
                      "post_comment_allowed": false,
                      "post_comment_displayed": false,
                      "post_files_allowed": false,
                      "post_video_allowed": false,
                      "post_video_url": null,
                      "post_pinned": false
                    }]
                  }
                }
        '400':
          description: Bad request
          content:
            text/plain:
              example: Missing required parameter
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: ""
        '500':
          description: Internal server error
          content:
            text/plain:
              example: Error parsing data
  /fundtype:
    get:
      description: Get Fund Type
      tags:
        - Fund Type
      parameters:
        - name: order_by
          in: query
          description: |-
              Order By
          required: false
          schema:
            type: string
            enum: [rec_order,fund_type_code,fund_type_name]
        - name: order_type
          in: query
          description: |-
              Order Type
          required: false
          schema:
            type: string
            enum: [ASC,DESC]
        - name: limit
          in: query
          description: |-
              Number of post (max 100 or choose no limit)
          required: false
          schema:
            type: integer
        - name: page
          in: query
          description: |-
              Page
          required: false
          schema:
            type: integer  
        - name: nolimit
          in: query
          description: |-
              Ignore limit and page
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                {
                  "status": {
                      "code": 200,
                      "message_server": "OK",
                      "message_client": "OK"
                  },
                  "data": [
                      {
                          "fund_type_key": 1,
                          "fund_type_code": "MM",
                          "fund_type_name": "Money Market",
                          "fund_type_desc": "Money Market",
                          "rec_order": 0,
                          "rec_image1": ""
                      },
                      {
                          "fund_type_key": 2,
                          "fund_type_code": "FI",
                          "fund_type_name": "Fix Income",
                          "fund_type_desc": "Fix Income",
                          "rec_order": 1,
                          "rec_image1": ""
                      },
                      {
                          "fund_type_key": 3,
                          "fund_type_code": "BF",
                          "fund_type_name": "Balance Fund",
                          "fund_type_desc": "Balance Fund",
                          "rec_order": 2,
                          "rec_image1": ""
                      },
                      {
                          "fund_type_key": 4,
                          "fund_type_code": "EQ",
                          "fund_type_name": "Ekuitas",
                          "fund_type_desc": "Ekuitas",
                          "rec_order": 3,
                          "rec_image1": ""
                      }
                  ]
                }
        '400':
          description: Bad request
          content:
            text/plain:
              example: Missing required parameter
        '401':
          description: Unauthorized
          content:
            text/plain:
              example: ""
        '500':
          description: Internal server error
          content:
            text/plain:
              example: Error parsing data
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Custom
