package models

type TrTransaction struct {
	TransactionKey        uint64   `db:"transaction_key"           json:"transaction_key"`
	IDTransaction         uint64   `db:"id_transaction"            json:"id_transaction"`
	BranchKey             uint64   `db:"branch_key"                json:"branch_key"`
	AgentKey              uint64   `db:"agent_key"                 json:"agent_key"`
	CustomerKey           uint64   `db:"customer_key"              json:"customer_key"`
	ProductKey            uint64   `db:"product_key"               json:"product_key"`
	TransStatusKey        uint64   `db:"trans_status_key"          json:"trans_status_key"`
	TransDate             string   `db:"trans_date"                json:"trans_date"`
	TransTypeKey          uint64   `db:"trans_type_key"            json:"trans_type_key"`
	TrxCode               string   `db:"trx_code"                  json:"trx_code"`
	NavDate               string   `db:"nav_date"                  json:"nav_date"`
	EntryMode             string   `db:"entry_mode"                json:"entry_mode"`
	TransAmount           float32  `db:"trans_amount"              json:"trans_amount"`
	TransUnit             float32  `db:"trans_unit"                json:"trans_unit"`
	TransUnitPercent      float32  `db:"trans_unit_percent"        json:"trans_unit_percent"`
	FlagRedemtAll         uint8    `db:"flag_redempt_all"          json:"flag_redempt_all"`
	FlagNewSub            uint8    `db:"flag_new_sub"              json:"flag_new_sub"`
	TransFeePercent       float32  `db:"trans_fee_pecent"          json:"trans_fee_pecent"`
	TransFeeAmount        float32  `db:"trans_fee_amount"          json:"trans_fee_amount"`
	ChargesFeeAmount      float32  `db:"charges_fee_amount"        json:"charges_fee_amount"`
	ServicesFeeAmount     float32  `db:"services_fee_amount"       json:"services_fee_amount"`
	TotalAmount           float32  `db:"total_amount"              json:"total_amount"`
	SettlementDate        string   `db:"settlement_date"           json:"settlement_date"`
	TransBankAccNo        string   `db:"trans_bank_accno"          json:"trans_bank_accno"`
	TransBankaccName      string   `db:"trans_bankacc_name"        json:"trans_bankacc_name"`
	TransBankKey          uint64   `db:"trans_bank_key"            json:"trans_bank_key"`
	TransRemarks          string   `db:"trans_remarks"             json:"trans_remarks"`
	TransReference        string   `db:"trans_reference"           json:"trans_reference"`
	PromoCode             string   `db:"promo_code"                json:"promo_code"`
	RiskWaiver            uint8    `db:"risk_waiver"               json:"risk_waiver"`
	AddtoAutoInvest       uint8    `db:"addto_auto_invest"         json:"addto_auto_invest"`
	TransSource           uint64   `db:"trans_source"              json:"trans_source"`
	ProceedDate           string   `db:"proceed_date"              json:"proceed_date"`
	ProceedAmount         float32  `db:"proceed_amount"            json:"proceed_amount"`
	SentDate              string   `db:"sent_date"                 json:"sent_date"`
	SentReference         string   `db:"sent_reference"            json:"sent_reference"`
	ConfirmedDate         string   `db:"confirmed_date"            json:"confirmed_date"`
	PostedDate            string   `db:"posted_date"               json:"posted_date"`
	PostedUnits           float32  `db:"posted_units"              json:"posted_units"`
	AcaKey                uint64   `db:"aca_key"                   json:"aca_key"`
	SettledDate           string   `db:"settled_date"              json:"settled_date"`
	RecOrder              *uint64   `db:"rec_order"                json:"rec_order"`
	RecStatus             uint8    `db:"rec_status"                json:"rec_status"`
	RecCreatedDate        *string   `db:"rec_created_date"         json:"rec_created_date"`
	RecCreatedBy          *string   `db:"rec_created_by"           json:"rec_created_by"`
	RecModifiedDate       *string   `db:"rec_modified_date"        json:"rec_modified_date"`
	RecModifiedBy         *string   `db:"rec_modified_by"          json:"rec_modified_by"`
	RecImage1             *string   `db:"rec_image1"               json:"rec_image1"`
	RecImage2             *string   `db:"rec_image2"               json:"rec_image2"`
	RecApprovalStatus     *uint8    `db:"rec_approval_status"      json:"rec_approval_status"`
	RecApprovalStage      *uint64   `db:"rec_approval_stage"       json:"rec_approval_stage"`
	RecApprovedDate       *string   `db:"rec_approved_date"        json:"rec_approved_date"`
	RecApprovedBy         *string   `db:"rec_approved_by"          json:"rec_approved_by"`
	RecDeletedDate        *string   `db:"rec_deleted_date"         json:"rec_deleted_date"`
	RecDeletedBy          *string   `db:"rec_deleted_by"           json:"rec_deleted_by"`
	RecAttributeID1       *string   `db:"rec_attribute_id1"        json:"rec_attribute_id1"`
	RecAttributeID2       *string   `db:"rec_attribute_id2"        json:"rec_attribute_id2"`
	RecAttributeID3       *string   `db:"rec_attribute_id3"        json:"rec_attribute_id3"`
}